pipelines:
  branches:
    develop:
      - step:
          name: Build Docker Image
          image: python:3.7.4-alpine3.10
          deployment: DevelopBuild
          services:
            - docker
          caches:
            - pip
          script:
            - export CI=true
            - pip3 install awscli
            - apk add --update nodejs npm
            - IMAGE="${AWS_ECR_REPOSITORY_DOMAIN}/${AWS_ECR_IMAGE_NAME}"
            - PACKAGE_VERSION=`node -p "require('./package.json').version"`
            - TAG=$PACKAGE_VERSION
            - aws configure set aws_access_key_id "${AWS_ACCESS_KEY_ID}"
            - aws configure set aws_secret_access_key "${AWS_SECRET_ACCESS_KEY}"
            - eval $(aws ecr get-login --no-include-email --region ${AWS_ACCESS_KEY_REGION} | sed 's;https://;;g')
            - docker build -t $IMAGE:$TAG .
            - docker tag $IMAGE:$TAG $AWS_ECR_REPOSITORY_DOMAIN/$AWS_ECR_IMAGE_NAME:$TAG
            - docker tag $IMAGE:$TAG $AWS_ECR_REPOSITORY_DOMAIN/$AWS_ECR_IMAGE_NAME:latest
            - docker push $IMAGE








 
